os:
  - linux

env:
  global:
    - CURRENT_BRANCH=$(git ls-remote origin | sed -n "\|$TRAVIS_COMMIT\s\+refs/heads/|{s///p}")

language: android

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - sys-img-armeabi-v7a-google_apis-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support
jdk: oraclejdk8

sudo: false

addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid

before_install:
  - echo "Install gradle and flutter bin"
  - cd ..

  - wget https://services.gradle.org/distributions/gradle-4.10.3-bin.zip
  - unzip -qq gradle-4.10.3-bin.zip
  - export GRADLE_HOME=`pwd`/gradle-4.10.3
  - export PATH=$GRADLE_HOME/bin:$PATH

  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

  - sdkmanager --list

  - git clone https://github.com/flutter/flutter.git
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH

install:
  - echo "Start install dependencies"
  - cd $TRAVIS_BUILD_DIR
  - flutter doctor
  - flutter pub get

script:
  - echo  "Start test"
  - flutter test
  - echo "TRAVIS_TAG = $TRAVIS_TAG"
  - echo "TRAVIS_BUILD_NUMBER = $TRAVIS_BUILD_NUMBER"
  - echo "TRAVIS_BRANCH = $TRAVIS_BRANCH"
  - echo "CURRENT_BRANCH = $CURRENT_BRANCH"

before_deploy:
  - flutter build apk --build-name $TRAVIS_TAG --build-number $TRAVIS_BUILD_NUMBER --split-per-abi

deploy:
  provider: releases
  file:
    - "./build/app/outputs/apk/release/app-armeabi-v7a-release.apk"
    - "./build/app/outputs/apk/release/app-arm64-v8a-release.apk"
    - "./build/app/outputs/apk/app.apk"
  skip-cleanup: true
  edge: true
  on:
    tags: true
    condition: $CURRENT_BRANCH = master

cache:
  directories:
    - $HOME/.pub-cache
